mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('twitter.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from .views import IndexView,UserCreateView,HomeView

app_name = 'polls'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('home/', HomeView.as_view(), name='home'),
]

mysite/polls/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate


class IndexView(TemplateView):
    template_name = "polls/signup.html"

# Create your views here.

class UserCreateView(FormView):
    form_class = UserCreationForm
    template_name = 'polls/create.html'
    success_url = reverse_lazy('polls:home')
    def form_valid(self, form):
        print(self.request.POST['next'])
        if self.request.POST['next'] == 'back':
            return render(self.request, 'polls/create.html', {'form': form})
        elif self.request.POST['next'] == 'confirm':
            return render(self.request, 'polls/create_confirm.html', {'form': form})
        elif self.request.POST['next'] == 'regist':
            form.save()
            # 認証
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
            )
            # ログイン
            login(self.request, user)
            return super().form_valid(form)
        else:
            # 通常このルートは通らない
            return redirect(reverse_lazy('polls:home'))

class HomeView(TemplateView):
    template_name = "polls/home.html"

mysite/polls/templates/polls/app_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
  <title>{% block title %}twitter home{% endblock %}</title>
</head>
<body>
  <header>
    <nav class="header-inner">
      <a href="" class="logo-title">Twitter</a>
      <div class="header-menu">
        {% if user.is_authenticated %}
        <ul class="header-menu-list">
          <li><a class="header-item" href="">ユーザー情報</a></li>
          <li><a class="header-item" href="">ログアウト</a></li>
        </ul>
        {% else %}
        <ul class="header-menu-list">
          <li><a class="header-item" href="">ログイン</a></li>
          <li><a class="header-item" href="{% url 'polls:create' %}">ユーザー登録</a></li>
        </ul>
        {% endif %}
      </div>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

mysite/polls/templates/polls/create.html
{% extends 'polls/signup_base.html' %}

{% block title %}twitter ユーザー登録{% endblock %}

{% block content %}
  <h1 class="signup-title">ユーザー登録</h1>
  <div class="create">
    <form action="" method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <div class="button-center"><button class="confirm" name="next" value="confirm" type="submit">確認</button></div>
    </form>
  </div>
{% endblock %}

mysite/polls/templates/polls/create_confirm.html
{% extends 'polls/signup_base.html' %}

{% block title %}twitter ユーザー確認{% endblock %}

{% block content %}
  <h1 class="signup-title">ユーザー確認</h1>
  <table>
    <tr><td>お名前</td><td>{{form.cleaned_data.username}}</td></tr>
    <tr><td>パスワード</td><td>********</td></tr>
  </table>
  <form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
      {{field.as_hidden}}
    {% endfor %}
    <div class="button-center">
      <button class="back" name="next" value="back" type="submit">修正</button>
      <button class="regist" name="next" value="regist" type="submit">登録</button>
    </div>
  </form>
{% endblock %}

mysite/polls/templates/polls/home.html
{% extends 'polls/app_base.html' %}

{% block content %}
  <div class="home-content">
    <h2>登録成功！</h2>
  </div>
{% endblock %}

mysite/polls/templates/polls/signup.html
{% extends 'polls/signup_base.html' %}

{% block title %}twitterを始めよう！{% endblock %}

{% block content %}
  <h1 class="signup-title">twitterを始めよう</h1>
  <a href="{% url 'polls:create' %}" class="create-account">アカウント作成</a>
  <a href="" class="login">ログイン</a>
{% endblock %}

mysite/polls/templates/polls/signup_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'polls/style.css' %}">
  <title>{% block title %}twitter signup{% endblock %}</title>
</head>
<body>
  <div class="start-content">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>