mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('twitter.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from .views import IndexView,UserCreateView,HomeView

app_name = 'polls'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('home/', HomeView.as_view(), name='home'),
]

mysite/twitter/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import IndexView, UserInputView, UserConfirmView, UserCreateView, HomeView, CreateTweet, ProfileView, follow_view, unfollow_view, like,unlike

app_name = 'twitter'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('input/', UserInputView.as_view(), name='input'),
    path('confirm/', UserConfirmView.as_view(), name='confirm'),
    path('create/', UserCreateView.as_view(), name='create'),
    path('home/', HomeView.as_view(), name='home'),
    path('home/<int:pk>/', HomeView.as_view(), name='home'),
    path('tweet/', CreateTweet.as_view(), name='tweet'),
    path("<int:tweet_id>/like/", like, name="like"),
    path("<int:tweet_id>/unlike/", unlike, name="unlike"),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/follow', follow_view, name='follow'),
    path('profile/<int:pk>/unfollow', unfollow_view, name='unfollow'),
]

mysite/twitter/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


class Tweet(models.Model):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, default="")
    text = models.CharField(max_length=200)
    like = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.text


class Like(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='like_user')
    tweet = models.ForeignKey(
        Tweet, on_delete=models.CASCADE, related_name="tweet")


class FriendShip(models.Model):
    follower = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='followee_friendships')
    followee = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='follower_friendships')

    class Meta:
        unique_together = ('follower', 'followee')

    def __str__(self):
        return (str(self.follower)+'⇔' + str(self.followee))

mysite/twitter/forms.py
from django import forms
from .models import Tweet


class TweetForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(
        attrs={'cols': '40', 'rows': '5', 'max_length': '200'}))

    class Meta:
        model = Tweet
        fields = ("user", "text")

mysite/twitter/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.views import generic
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib import messages
from .forms import TweetForm
from .models import Tweet, FriendShip, Like
from .helpers import get_current_user


class IndexView(generic.TemplateView):
    template_name = "twitter/signup.html"

# Create your views here.


class UserInputView(generic.FormView):
    form_class = UserCreationForm
    template_name = 'twitter/input.html'

    def form_valid(self, form):
        return render(self.request, 'twitter/input.html', {'form': form})


class UserConfirmView(generic.FormView):
    form_class = UserCreationForm

    def form_valid(self, form):
        return render(self.request, 'twitter/confirm.html', {'form': form})

    def form_invalid(self, form):
        return render(self.request, 'twitter/input.html', {'form': form})


class UserCreateView(generic.FormView):
    form_class = UserCreationForm
    success_url = reverse_lazy('twitter:home')

    def form_valid(self, form):
        # 認証
        user = form.save()
        # ログイン
        login(self.request, user)
        return super().form_valid(form)

    def form_invalid(self, form):
        return render(self.request, 'twitter/input.html', {'form': form})


class HomeView(LoginRequiredMixin, generic.FormView):
    template_name = "twitter/home.html"
    form_class = TweetForm
    login_url = '/'

    def get_context_data(self, **kwargs):
        initial_dict = {'user': self.request.user}
        form_class = TweetForm(self.request.POST or None, initial=initial_dict)
        # TemplateViewにあるcontextを取得
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        # contextにformというキーでformという変数を追加
        context["form"] = form_class
        # contextにtweetsというキーでツイート一覧を追加
        context["tweets"] = Tweet.objects.all()
        context['my_likes_ids'] = Like.objects.filter(
            user=self.request.user).values_list('tweet_id', flat=True)
        return context
    def get_success_url(self):
        return reverse('twitter:profile', kwargs={'pk': self.user.id})


class CreateTweet(generic.FormView):
    success_url = reverse_lazy('twitter:home')
    form_class = TweetForm

    def form_valid(self, form):
        form_class = TweetForm(self.request.POST)
        post = form_class.save(commit=False)
        post.user = self.request.user
        post = form.save()
        return redirect('twitter:home')

    def form_invalid(self, form):
        return render(self.request, 'twitter/home.html', {'form': form})


class ProfileView(generic.DetailView):
    model = User
    template_name = "twitter/profile.html"

    def get_context_data(self, **kwargs):
        follower = User.objects.get(username=self.request.user)
        followee = User.objects.get(id=self.kwargs['pk'])
        context = super(ProfileView, self).get_context_data(**kwargs)
        user_id = self.kwargs['pk']
        context['user_id'] = user_id
        context['current_user'] = get_current_user(self.request)
        context['followee'] = FriendShip.objects.filter(
            followee=followee).count()
        context['follower'] = FriendShip.objects.filter(
            follower=followee).count()
        context['followees'] = FriendShip.objects.filter(followee=followee)
        context['followers'] = FriendShip.objects.filter(follower=followee)
        if user_id is not context['current_user'].username:
            result = FriendShip.objects.filter(
                follower=follower).filter(followee=followee)
            context['connected'] = True if result else False
        return context

def like(request, tweet_id):
    tweet = Tweet.objects.get(pk=tweet_id)
    like_num = Like.objects.filter(
        user=request.user).filter(tweet=tweet).count()
    if like_num > 0:
        return redirect('twitter:home')
    tweet.like += 1
    tweet.save()
    like = Like()
    like.user = request.user
    like.tweet = tweet
    like.save()
    return redirect('twitter:home')

def unlike(request, tweet_id):
    tweet = Tweet.objects.get(pk=tweet_id)
    like_num = Like.objects.filter(
        user=request.user).filter(tweet=tweet).count()
    if like_num == 0:
        return redirect('twitter:home')
    liking = Like.objects.get(tweet_id=tweet_id, user=request.user)
    liking.delete()
    tweet.like -= 1
    tweet.save()
    return redirect('twitter:home')

def follow_view(request, *args, **kwargs):
    follower = User.objects.get(username=request.user)
    followee = User.objects.get(id=kwargs['pk'])
    if follower == followee:
        messages.warning(request, '自分自身はフォローできません')
        return redirect('twitter:profile', pk=followee.id)
    created = FriendShip.objects.get_or_create(
        follower=follower, followee=followee)
    if (created):
        messages.success(request, '{}をフォローしました'.format(followee.username))
    else:
        messages.warning(
            request, 'あなたはすでに{}をフォローしています'.format(followee.username))
    return redirect('twitter:profile', pk=followee.id)


def unfollow_view(request, *args, **kwargs):
    follower = User.objects.get(username=request.user)
    followee = User.objects.get(id=kwargs['pk'])
    if follower == followee:
        messages.warning(request, '自分自身のフォローを外せません')
    else:
        unfollow = FriendShip.objects.get(follower=follower, followee=followee)
        unfollow.delete()
        messages.success(
            request, 'あなたは{}のフォローを外しました'.format(followee.username))
    return redirect('twitter:profile', pk=followee.id)

mysite/twitter/templates/twitter/app_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'twitter/style.css' %}">
  <title>{% block title %}twitter home{% endblock %}</title>
</head>
<body>
  <header>
    <nav class="header-inner">
      <a href="{% url 'twitter:home' %}" class="logo-title">Twitter</a>
      <div class="header-menu">
        {% if user.is_authenticated %}
        <ul class="header-menu-list">
          <li><a class="header-item" href="{% url 'logout' %}">ログアウト</a></li>
        </ul>
        {% else %}
        <ul class="header-menu-list">
          <li><a class="header-item" href="{% url 'login' %}">ログイン</a></li>
          <li><a class="header-item" href="{% url 'twitter:create' %}">ユーザー登録</a></li>
        </ul>
        {% endif %}
      </div>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

mysite/twitter/templates/twitter/confirm.html
{% extends 'twitter/signup_base.html' %}

{% block title %}twitter ユーザー確認{% endblock %}

{% block content %}
  <h1 class="signup-title">ユーザー確認</h1>
  <table>
    <tr><td>お名前</td><td>{{form.cleaned_data.username}}</td></tr>
    <tr><td>パスワード</td><td>********</td></tr>
  </table>
  <!-- 修正 -->
  <div class="button-center button-row">
    <form action="{% url 'twitter:input' %}" method="POST">
      {% csrf_token %}
      {% for field in form %}
        {{field.as_hidden}}
      {% endfor %}
      <button class="back-btn" type="submit">修正</button>
    </form>
    <!-- 登録 -->
    <form action="{% url 'twitter:create' %}" method="POST">
      {% csrf_token %}
      {% for field in form %}
        {{field.as_hidden}}
      {% endfor %}
      <button class="regist-btn" type="submit">登録</button>
    </form>
  </div>
{% endblock %}

mysite/twitter/templates/twitter/create.html
{% extends 'twitter/signup_base.html' %}

{% block title %}twitter ユーザー登録{% endblock %}

{% block content %}
  <h1 class="signup-title">ユーザー登録</h1>
  <div class="create">
    <form action="" method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <div class="button-center"><button class="confirm" name="next" value="confirm" type="submit">確認</button></div>
    </form>
  </div>
{% endblock %}

mysite/twitter/templates/twitter/create_confirm.html
{% extends 'twitter/signup_base.html' %}

{% block title %}twitter ユーザー確認{% endblock %}

{% block content %}
  <h1 class="signup-title">ユーザー確認</h1>
  <table>
    <tr><td>お名前</td><td>{{form.cleaned_data.username}}</td></tr>
    <tr><td>パスワード</td><td>********</td></tr>
  </table>
  <form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
      {{field.as_hidden}}
    {% endfor %}
    <div class="button-center">
      <button class="back" name="next" value="back" type="submit">修正</button>
      <button class="regist" name="next" value="regist" type="submit">登録</button>
    </div>
  </form>
{% endblock %}

mysite/twitter/templates/twitter/home.html
{% extends 'twitter/app_base.html' %}

{% block content %}
<div class="home-content">
  <div class="container">
    <div class="row">
      <div class="col-6 tweet-list">
        <h4>ツイート</h4>
        {% for tweet in tweets %}
          <div class="post">
            <div class="user"><a href={% url 'twitter:profile' tweet.user.id %}><span>{{tweet.user}}</span></a></div>
            <p>{{ tweet.text }}</p>
            <div class="btn-right">
              {% if tweet.id in my_likes_ids %}
                <a href="{% url 'twitter:unlike' tweet.id %}" class="like-btn"><i class="fas fa-heart"></i><span class="like-num">{{tweet.like}}</span></a>
              {% else %}
                <a href="{% url 'twitter:like' tweet.id %}" class="prev-like-btn"><i class="far fa-heart"></i><span class="like-num">{{tweet.like}}</span></a>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="row">
      <div class="tweet-form col-6">
        <form method="POST" action="{% url 'twitter:tweet' %}">
          {% csrf_token %}
          {{form.as_p}}
          <input class="tweet-btn" type="submit" value="ツイート">
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

mysite/twitter/templates/twitter/input.html
{% extends 'twitter/signup_base.html' %}

{% block title %}twitter ユーザー登録{% endblock %}

{% block content %}
  <h1 class="signup-title">ユーザー登録</h1>
  <div class="create">
    <form action="{% url 'twitter:confirm' %}" method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <div class="button-center"><button class="confirm-btn" type="submit">確認</button></div>
    </form>
  </div>
{% endblock %}

mysite/twitter/templates/twitter/profile.html
{% extends 'twitter/app_base.html' %}

{% block content %}
<div class="home-content">
  <div class="container">
    <div class="row">
      <div class="col-6 user-profile">
        <h4 class="user-title">{{ user.username }}　のプロフィール</h4>
        {% if current_user != user  %}
          {% if connected %}
            <a href="{% url 'twitter:unfollow' user.id %}" class="btn btn-dark">フォロー解除</a>
          {% else %}
            <a href="{% url 'twitter:follow' user.id %}" class="btn btn-light">フォロー</a>
          {% endif %}
        {% endif %}
        {% if messages %}
          <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
        <div></div>
        <div class="follower-content">
          <h5>{{ user.username }}がフォローしている人<span class="follower-num">{{ follower }}</span> </h5>
          <div class="scrollable">
            <ul class="follower-members">
              {% for f in followers %}
              <li class="follower-member">{{ f.followee }}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="followee-content">
          <h5>{{ user.username }}をフォローしている人 <span class="followee-num">{{ followee }}</span> </h5>
          <div class="scrollable">
            <ul class="followee-members">
              {% for f in followees %}
              <li class="followee-member">{{ f.follower }}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

mysite/twitter/templates/twitter/signup.html
{% extends 'twitter/signup_base.html' %}

{% block title %}twitterを始めよう！{% endblock %}

{% block content %}
  <h1 class="signup-title">twitterを始めよう</h1>
  <a href="{% url 'twitter:input' %}" class="create-account-btn-lg">アカウント作成</a>
  <a href="{% url 'login' %}" class="login-btn-lg">ログイン</a>
{% endblock %}

mysite/twitter/templates/twitter/signup_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'twitter/style.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <div class="signup-content">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>